############################################################
# +------------------------------------------------------+ #
# |                     Configuration                    | #
# +------------------------------------------------------+ #
############################################################
# This is the main configuration file for Allium.
# For more information, visit: https://github.com/castledking/Allium

# Language for lang.yml
lang: en
server-name: "Unknown Server"

############################################################
# +------------------------------------------------------+ #
# |                 Discord Settings                     | #
# +------------------------------------------------------+ #
############################################################

# Discord integration settings
discord:
  # Webhook for escalation command
  escalate_webhook: ""
  
  # List of role IDs to mention in escalation messages
  escalate_mentions: []
  
  # Bot display name (optional)
  bot_name: "Server Escalation"
  
  # Bot avatar URL (optional)
  bot_avatar: ""

############################################################
# +------------------------------------------------------+ #
# |                 Maintenance Settings                 | #
# +------------------------------------------------------+ #
############################################################

maintenance: # A list of player UUIDs that bypass maintenance mode.
  bypass: []

############################################################
# +------------------------------------------------------+ #
# |                 Chat Settings                        | #
# +------------------------------------------------------+ #
############################################################

# This section configures various aspects of the chat system.
# Each setting is explained in detail below.  Make sure to
# save and reload/restart the server after making changes.

# Available placeholders:
#   <player> - The player's real name.
#   <display_name> or <name> - The player's display name. (/nick)
#   <prefix> - The player's prefix.
#   <suffix> - The player's suffix.
#   <message> - The message being sent.
#   %{placeholder}% - PlaceholderAPI support.

enable-chat-formatting: true # Vault or forks of Vault are required for this to work.
block-unicode: true # Set to false to allow Unicode symbols

chat-format:
  default: "<prefix> &a<player>&f: &f<message>"
  groups:
    #admin: "&4[Admin] &c<player>&f: <message>"
    #moderator: "&2[Mod] &a<player>&f: <message>"
    #vip: "&6[VIP] &e<player>&f: <message>"

############################################################
# +------------------------------------------------------+ #
# |                 General Settings                     | #
# +------------------------------------------------------+ #
############################################################

creative-manager:
  # Here you can add blocks and entities that will be
  # blacklisted from being place, broken or spawned in creative mode.
  #
  # Note: this blacklist is only used if the player
  # already has the appropriate bypass permission:
  # Currently handling:
  # - core.gamemode.creative.break
  # - core.gamemode.creative.place
  # - core.gamemode.creative.spawn
  blacklist:
    blocks: []
    entities: []

# Creeper explosion regen speed (0 = disabled, 1 = slowest, 10 = fastest)
creeper-explosion-regen-speed: 5

allow-unsafe-enchants: false
#  Should we allow unsafe enchantments to be applied?
#  Unsafe enchantments are those that exceed the normal level limits.
#  Default: false

# List of players eligible to redeem a rank.
# Format: "<UUID>:<rank_name_lowercase>"
# Example: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:iron"
players-to-redeem:
  - "00000000-0000-0000-0000-000000000001:iron"
  - "00000000-0000-0000-0000-000000000002:gold"

redeem-settings:
  # Commands to run for each rank when a player redeems.
  # Ranks are determined by the suffix in the 'players-to-redeem' list (e.g., 'uuid:iron' means the rank is 'iron').
  # Placeholders: {player} (player's name)
  commands-to-run:
    iron:
      - "lp user {player} parent set iron"
      - "minecraft:xp add {player} 100 points"
      - "eco give {player} 500"
    gold:
      - "lp user {player} parent set gold"
      - "minecraft:xp add {player} 250 points"
      - "eco give {player} 1500"
    emerald:
      - "lp user {player} parent set emerald"
      - "minecraft:xp add {player} 500 points"
      - "eco give {player} 3000"
    netherite:
      - "lp user {player} parent set netherite"
      - "minecraft:xp add {player} 1000 points"
      - "eco give {player} 5000"

############################################################
# +------------------------------------------------------+ #
# |                   Give Settings                      | #
# +------------------------------------------------------+ #
############################################################

give:
  # Whether to drop overflow items when player's inventory is full
  drop-overflow-items: true
  
  # Maximum number of items that can be dropped when inventory is full
  # Set to -1 for unlimited, or any positive number to limit drops
  max-items-dropped: 64

############################################################
# +------------------------------------------------------+ #
# |                 Command Settings                     | #
# +------------------------------------------------------+ #
############################################################

explode-command:
  default: 2
  # Default radius of the explosion caused by the /explode command.
  # Must be within the 'min' and 'max' values specified below.
  # Default: 2
  max: 10
  # Maximum allowed radius for the /explode command.
  # Default: 10
  min: 1
  # Minimum allowed radius for the /explode command.
  # Default: 1

heal:
  cooldown: 60
  # Time in seconds players without core.heal.nocooldown

feed:
  cooldown: 60
  # Time in seconds players without core.feed.nocooldown

teleport:
  delay: 3
  # Time in seconds players without core.tpa.nodelay
  cooldown: 30
  # Time in seconds players without core.tpa.nocooldown
  expire: 120
  # Time in seconds a request expires.
  tppet-radius: 30
  # Maximum radius in blocks the player can be from the pet.
  auto-disable:
    # Whether to auto-disable entity teleport mode after teleporting entities
    # If set to false, entity selection will remain active after teleporting
    # This applies to non-admin players only (admins always keep selection active)
    enabled: true
    # Whether to auto-disable pet teleport mode after teleporting pets
    # If set to false, pet selection will remain active after teleporting
    pets-enabled: true

############################################################
# +------------------------------------------------------+ #
# |                 Economy Settings                     | #
# +------------------------------------------------------+ #
############################################################

economy:
  # Currency symbol to use when displaying money amounts
  # Examples: $, €, £, ¥, ₽, etc.
  currency-symbol: "$"
  
  # Default starting balance for new players
  starting-balance: 100.00
  
  # Maximum number of decimal places to display
  decimal-places: 2
  
  # Whether to show the currency symbol before or after the amount
  # true = $100, false = 100$
  symbol-before-amount: true
  
  # Whether to add a space between the amount and symbol
  # true = 100 $, false = 100$
  # Only applies when symbol-before-amount is false
  space-between: false

############################################################
# +------------------------------------------------------+ #
# |                 World Settings                       | #
# +------------------------------------------------------+ #
############################################################

world-defaults:
  world: # Replace 'world' with the actual world name
    - send-command-feedback: false
      #  Whether or not command feedback (e.g., "Command executed successfully")
      #  is sent to players in this world.
      #  Default: false

#  You can add more worlds here by creating new sections like this:
#  world_nether:
#    - send-command-feedback: true
#
#  world_the_end:
#    - send-command-feedback: false

############################################################
# +------------------------------------------------------+ #
# |                 Debug Settings                       | #
# +------------------------------------------------------+ #
############################################################

debug-mode: true
