############################################################
# +------------------------------------------------------+ #
# |            Chat Settings Configuration               | #
# +------------------------------------------------------+ #
############################################################

# This section configures various aspects of the chat system.
# Each setting is explained in detail below.  Make sure to
# save and reload/restart the server after making changes.

# Available placeholders:
#   <player> - The player's real name.
#   <display_name> or <name> - The player's display name. (/nick)
#   <prefix> - The player's prefix.
#   <suffix> - The player's suffix.
#   <message> - The message being sent.
#   %{placeholder}% - PlaceholderAPI support.


# Enable debug mode to see prefix information in console
debug-mode: false

enable-chat-formatting: true
# Vault or forks of Vault are required for this to work.

chat-format:
  default: "<prefix> &a<player>&f: &f<message>"
  groups:
    #default: "&7<player>&f: <message>" # Default Group Format
    #admin: "&4[Admin] &c<player>&f: <message>"
    #moderator: "&2[Mod] &a<player>&f: <message>"
    #vip: "&6[VIP] &e<player>&f: <message>"



############################################################
#  General Settings                                        #
############################################################

allow-unsafe-enchants: false
#  Should we allow unsafe enchantments to be applied?
#  Unsafe enchantments are those that exceed the normal level limits.
#  Default: false

############################################################
#  Command Settings                                        #
############################################################

explode-command:
  default: 2
  #  The default radius of the explosion caused by the /explode command.
  #  Must be within the 'min' and 'max' values specified below.
  #  Default: 2

  max: 10
  #  The maximum allowed radius for the /explode command.
  #  Players cannot use a value higher than this.
  #  Default: 10

  min: 1
  #  The minimum allowed radius for the /explode command.
  #  Players cannot use a value lower than this.
  #  Default: 1

############################################################
#  World-Specific Defaults                                  #
############################################################

world-defaults:
  world: # Replace 'world' with the actual world name
    - send-command-feedback: false
      #  Whether or not command feedback (e.g., "Command executed successfully")
      #  is sent to players in this world.
      #  Default: false

#  You can add more worlds here by creating new sections like this:
#  world_nether:
#    - send-command-feedback: true
#
#  world_the_end:
#    - send-command-feedback: false