############################################################
# +------------------------------------------------------+ #
# |                     Configuration                    | #
# +------------------------------------------------------+ #
############################################################
# This is the main configuration file for SFCore.
# For more information, visit: https://github.com/castledking/SFCore

# Language for lang.yml
lang: en

############################################################
# +------------------------------------------------------+ #
# |                 Chat Settings                        | #
# +------------------------------------------------------+ #
############################################################

# This section configures various aspects of the chat system.
# Each setting is explained in detail below.  Make sure to
# save and reload/restart the server after making changes.

# Available placeholders:
#   <player> - The player's real name.
#   <display_name> or <name> - The player's display name. (/nick)
#   <prefix> - The player's prefix.
#   <suffix> - The player's suffix.
#   <message> - The message being sent.
#   %{placeholder}% - PlaceholderAPI support.

enable-chat-formatting: true # Vault or forks of Vault are required for this to work.
block-unicode: true # Set to false to allow Unicode symbols

chat-format:
  default: "<prefix> &a<player>&f: &f<message>"
  groups:
    #admin: "&4[Admin] &c<player>&f: <message>"
    #moderator: "&2[Mod] &a<player>&f: <message>"
    #vip: "&6[VIP] &e<player>&f: <message>"

############################################################
# +------------------------------------------------------+ #
# |                 General Settings                     | #
# +------------------------------------------------------+ #
############################################################

creative-manager:
  # Here you can add blocks and entities that will be
  # blacklisted from being place, broken or spawned in creative mode.
  #
  # Note: this blacklist is only used if the player
  # already has the appropriate bypass permission:
  # Currently handling:
  # - core.gamemode.creative.break
  # - core.gamemode.creative.place
  # - core.gamemode.creative.spawn
  blacklist:
    blocks: []
    entities: []

# Creeper explosion regen speed (0 = disabled, 1 = slowest, 10 = fastest)
creeper-explosion-regen-speed: 5

allow-unsafe-enchants: false
#  Should we allow unsafe enchantments to be applied?
#  Unsafe enchantments are those that exceed the normal level limits.
#  Default: false

# List of players eligible to redeem a rank.
# Format: "<UUID>:<rank_name_lowercase>"
# Example: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:iron"
players-to-redeem:
  - "00000000-0000-0000-0000-000000000001:iron"
  - "00000000-0000-0000-0000-000000000002:gold"

redeem-settings:
  # Commands to run for each rank when a player redeems.
  # Ranks are determined by the suffix in the 'players-to-redeem' list (e.g., 'uuid:iron' means the rank is 'iron').
  # Placeholders: {player} (player's name)
  commands-to-run:
    iron:
      - "lp user {player} parent set iron"
      - "minecraft:xp add {player} 100 points"
      - "eco give {player} 500"
    gold:
      - "lp user {player} parent set gold"
      - "minecraft:xp add {player} 250 points"
      - "eco give {player} 1500"
    emerald:
      - "lp user {player} parent set emerald"
      - "minecraft:xp add {player} 500 points"
      - "eco give {player} 3000"
    netherite:
      - "lp user {player} parent set netherite"
      - "minecraft:xp add {player} 1000 points"
      - "eco give {player} 5000"

redeem-items:
  enabled: true # Set to false to disable giving items on join and item-based redemption.

  item-definitions:
    # Define the appearance and NBT data for each rank's redeem item.
    # The rank key (e.g., 'iron') MUST match the rank suffix in the 'players-to-redeem' list.
    #
    # To use a player skull:
    # 1. Set 'material' to "PLAYER_HEAD".
    # 2. Add the 'skull-owner' field. It can accept:
    #    - A player's name (e.g., "Notch")
    #    - A player's UUID (e.g., "069a79f4-44e9-4726-a5be-fca90e38aaf5")
    #    - A HeadDatabase ID (e.g., "hdb:12345")
    #    - A Base64 texture value (a very long string).
    # When 'skull-owner' is present, 'banner-patterns' will be ignored if material is PLAYER_HEAD.
    iron:
      material: "PLAYER_HEAD"
      skull-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTYzYjg3ZWU2YTU1ZjJiZjAxMzViMjZiZDk2ZWMyNzllZGVkMTc1Zjk0OGMwMzZkODhhNjA3MjVlMTI3MzcxYyJ9fX0="  # Iron Block texture
      display-name: "&f&l✦ Iron Rank Voucher ✦"
      lore:
        - "&7Right-click to redeem your Iron rank!"
        - "&7Thank you for your support!"
        - ""
        - "&8&o* A solid foundation for your journey *"
      glow: true
    gold:
      material: "PLAYER_HEAD"
      skull-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTQ3OTZjMWRkOTM3NDk2NGIzNWIzNGIzMzI5ZTJkNTNhZGY4ZDQ3NDc1NTZkN2FkNDJlMzU5ZWRjN2UzZWQ2MiJ9fX0="  # Gold Block texture
      display-name: "&6&l★ Gold Rank Voucher ★"
      lore:
        - "&7Right-click to redeem your Gold rank!"
        - "&7Thank you for your continued support!"
        - ""
        - "&8&o* Shining bright like a treasure *"
      glow: true
    emerald:
      material: "PLAYER_HEAD"
      skull-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjcyYzA1ZGQ3NjI4OGY0MzI4YTI0MzkxYmY0NzI1ZmQyMjYwNTkyZGIzY2Y5YjJiYzIwMzJkZDA1OTZjZjQ0MCJ9fX0="  # Emerald Block texture
      display-name: "&a&l✪ Emerald Rank Voucher ✪"
      lore:
        - "&7Right-click to redeem your Emerald rank!"
        - "&7A symbol of true dedication!"
        - ""
        - "&8&o* Rare and valuable, just like you *"
      glow: true
    netherite:
      material: "PLAYER_HEAD"
      skull-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQ4YjQ5ZThiYWZiMWZlZmI0OTUzOWJlNGU4MmNjN2UyYTI0NGJmMDQyODEzNGI5YTgwNTkxYTE3YzFhZTNjYiJ9fX0="  # Netherite Block texture
      display-name: "&8&l✵ Netherite Rank Voucher ✵"
      lore:
        - "&7Right-click to redeem your Netherite rank!"
        - "&7Your ultimate support is legendary!"
        - ""
        - "&8&o* Forged in fire, stronger than diamond *"
      glow: true
    # You can add more rank vouchers following the same pattern
    # Example using HeadDatabase:
    # example_hdb:
    #   material: "PLAYER_HEAD"
    #   skull-owner: "hdb:1328"  # HeadDatabase ID
    #   display-name: "&d&l✧ Example Rank Voucher ✧"
    #   lore:
    #     - "&7Right-click to redeem your Example rank!"
    #   glow: true  
      # skull-owner: "MHF_Question" # Example: Minecraft-Heads default question mark head
      # skull-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4NzDkZmY2M2YxNzMyZGQ2MWEwN2NmMmU0Mzc0MyJ9fX0=" # Example: Base64 for a specific skin
      # display-name: "&e&lSkull Rank Voucher"
      # lore:
      #   - "&7Right-click to redeem your Skull Rank!"
      #   - "&7This item uses a custom skull."
      # glow: true

    # Banner pattern example (for reference):
    # banner_example:
    #   material: "RED_BANNER"
    #   display-name: "&c&l⚑ Banner Example Voucher ⚑"
    #   lore:
    #     - "&7This is an example of a banner-based voucher"
    #     - "&7with custom patterns applied."
    #     - ""
    #     - "&8&o* Shows how to use banner patterns *"
    #   # Banner patterns are applied in order from top to bottom
    #   # Format: "DYE_COLOR:PATTERN_TYPE"
    #   # See Bukkit DyeColor and PatternType enums for all options
    #   banner-patterns:
    #     - "BLACK:GRADIENT_UP"       # Base gradient from bottom
    #     - "ORANGE:STRIPE_CENTER"    # Center horizontal stripe
    #     - "YELLOW:CIRCLE_MIDDLE"    # Center circle
    #     - "WHITE:BORDER"            # Border around the edge
    #     - "RED:SKULL"               # Skull pattern in the middle
    #   glow: true

############################################################
# +------------------------------------------------------+ #
# |                   Give Settings                      | #
# +------------------------------------------------------+ #
############################################################

give:
  # Whether to drop overflow items when player's inventory is full
  drop-overflow-items: true
  
  # Maximum number of items that can be dropped when inventory is full
  # Set to -1 for unlimited, or any positive number to limit drops
  max-items-dropped: 64

############################################################
# +------------------------------------------------------+ #
# |                 Command Settings                     | #
# +------------------------------------------------------+ #
############################################################

explode-command:
  default: 2
  # Default radius of the explosion caused by the /explode command.
  # Must be within the 'min' and 'max' values specified below.
  # Default: 2
  max: 10
  # Maximum allowed radius for the /explode command.
  # Default: 10
  min: 1
  # Minimum allowed radius for the /explode command.
  # Default: 1

heal:
  cooldown: 60
  # Time in seconds players without core.heal.nocooldown

feed:
  cooldown: 60
  # Time in seconds players without core.feed.nocooldown

teleport:
  delay: 3
  # Time in seconds players without core.tpa.nodelay
  cooldown: 30
  # Time in seconds players without core.tpa.nocooldown
  expire: 120
  # Time in seconds a request expires.
  tppet-radius: 30
  # Maximum radius in blocks the player can be from the pet.
  auto-disable:
    # Whether to auto-disable entity teleport mode after teleporting entities
    # If set to false, entity selection will remain active after teleporting
    # This applies to non-admin players only (admins always keep selection active)
    enabled: true
    # Whether to auto-disable pet teleport mode after teleporting pets
    # If set to false, pet selection will remain active after teleporting
    pets-enabled: true

############################################################
# +------------------------------------------------------+ #
# |                 Economy Settings                     | #
# +------------------------------------------------------+ #
############################################################

economy:
  # Currency symbol to use when displaying money amounts
  # Examples: $, €, £, ¥, ₽, etc.
  currency-symbol: "$"
  
  # Default starting balance for new players
  starting-balance: 100.00
  
  # Maximum number of decimal places to display
  decimal-places: 2
  
  # Whether to show the currency symbol before or after the amount
  # true = $100, false = 100$
  symbol-before-amount: true
  
  # Whether to add a space between the amount and symbol
  # true = 100 $, false = 100$
  # Only applies when symbol-before-amount is false
  space-between: false

############################################################
# +------------------------------------------------------+ #
# |                 World Settings                       | #
# +------------------------------------------------------+ #
############################################################

world-defaults:
  world: # Replace 'world' with the actual world name
    - send-command-feedback: false
      #  Whether or not command feedback (e.g., "Command executed successfully")
      #  is sent to players in this world.
      #  Default: false

#  You can add more worlds here by creating new sections like this:
#  world_nether:
#    - send-command-feedback: true
#
#  world_the_end:
#    - send-command-feedback: false

############################################################
# +------------------------------------------------------+ #
# |                 Debug Settings                       | #
# +------------------------------------------------------+ #
############################################################

debug-mode: true
