name: SFCore
version: 1.0
main: net.survivalfun.core.PluginStart
api-version: 1.21
author: towkio
description: "Survival Fun Core"
soft-depend: [LuckPerms, PlaceholderAPI, Vault]

commands:
  redeem:
    description: Allows eligible players to redeem a rank and rewards.
    usage: /redeem
    aliases: [claimrank] # Optional alias
  explode:
    description: "Explodes target player"
    usage: "/explode <player> [modifier]"
    permission: core.explode
  gc:
    description: "Displays server details"
    usage: "/gc"
    permission: core.gc
  give:
    description: "Give items to players"
    usage: "/give <player> <item> <amount>"
    permission: core.give
    aliases: [i]
  itemdb:
    description: "Shows item/block info"
    usage: "/itemdb"
    permission: core.itemdb
  heal:
    description: "Heal players"
    usage: "/heal [player]"
    permission: core.heal
  feed:
    description: "Feed players"
    usage: "/feed [player]"
    permission: core.feed
  core:
    description: "Core plugin command. Subcommands: reload, debug, voucher, etc."
    usage: "/core"
    permission: core.admin
  rename:
    description: "Rename item in main hand"
    usage: "/rename <name>"
    permission: core.rename
  lore:
    description: "Mange lore in main hand"
    usage: "/lore <add|remove|clear> <text>"
    permission: core.lore
  god:
    description: "Toggle god mode"
    usage: "/god || /god <player>"
    permission: core.god
  more:
    description: "Adds more items to your inventory"
    usage: "/more"
    permission: core.more
  fly:
    description: "Toggle flight"
    usage: "/fly || /fly <player>"
    permission: core.fly
  gamemode:
    description: "Change gamemode"
    usage: "/gamemode <gamemode> <player>"
    permission: core.gamemode
    aliases: [gm, gmc, gms, gma, gmsp, survival, creative, adventure, spectator]
  nv:
    description: "Toggle night vision"
    usage: "/nv"
    permission: core.nv
  msg:
    description: "Send a private message to player"
    usage: "/msg <player> <message>"
    aliases: [ tell, w, whisper, pm, message, m, t ]

  reply:
    description: "Reply to the last message received"
    usage: "/reply <message>"
    aliases: [ r ]

  mail:
    description: "Send or read offline messages"
    usage: "/mail <read|send|clear|gift|claim> [player] [message]"

  spy:
    description: "Spy on private messages"
    usage: "/spy [player]"
  help:
    description: "Displays help"
    usage: "/help [command]"
    aliases: [commands]
  spawn:
    description: "Teleports you to spawn"
    usage: "/spawn"
    aliases: [setspawn]
  
  # Teleport Commands
  tp:
    description: "Teleport to a player or location"
    usage: "/tp [player] or /tp [x] [y] [z]"
    aliases: [tpo, teleport, back]
    permission: core.tp
  
  tpa:
    description: "Request to teleport to a player"
    usage: "/tpa <player>"
    permission: core.tpa
  
  tpaccept:
    description: "Accept a teleport request"
    usage: "/tpaccept [player]"
    aliases: [tpyes]
    permission: core.tpa
  
  tpdeny:
    description: "Deny a teleport request"
    usage: "/tpdeny [player]"
    aliases: [tpno]
    permission: core.tpa
  
  tppet:
    description: "Teleport to your pets"
    usage: "/tppet"
    permission: core.tp
  
  tppos:
    description: "Teleport to specific coordinates"
    usage: "/tppos <x> <y> <z> [yaw] [pitch]"
    permission: core.tppos
  
  tphere:
    description: "Bring a player to your location"
    usage: "/tphere <player>"
    aliases: [s]
    permission: core.tphere
  
  tpahere:
    description: "Request a player to teleport to you"
    usage: "/tpahere <player>"
    permission: core.tpahere
  
  tptoggle:
    description: "Toggle teleport requests"
    usage: "/tptoggle [player]"
    permission: core.tptoggle
  
  top:
    description: "Teleport to the highest block"
    usage: "/top"
    permission: core.top
  
  bottom:
    description: "Teleport to the lowest block"
    usage: "/bottom"
    permission: core.bottom

  whois:
    description: "Displays detailed information about a player."
    usage: "/whois <player>"
    permission: core.whois

permissions:
  core.*:
    default: op
  core.admin:
    default: op
  core.spy:
    default: op

  core.gamemode.others:
    default: op
  core.gamemode.survival:
    default: op
  core.gamemode.creative:
    default: op
  core.gamemode.creative.bypass.*:
    default: op
  core.gamemode.creative.bypass.inventory:
    default: op
  core.gamemode.adventure:
    default: op
  core.gamemode.spectator:
    default: op
  core.gamemode:
    default: op
  core.nv:
    default: op

  core.tp:
    default: op
  core.tp.others:
    default: op
  core.tpa:
    default: true
  core.tpa.nodelay:
    default: op
  core.tpa.nocooldown:
    default: op
  core.voucher.give:
    description: "Allows giving rank vouchers via /core voucher give"
    default: op # Or 'false' if you want only core.admin to grant it implicitly
  core.tppos:
    default: op
  core.tphere:
    default: op
  core.tpahere:
    default: true
  core.tpall:
    default: op
  core.tptoggle:
    default: true
  core.tptoggle.bypass:
    default: op
  core.tp.offline:
    default: op
  core.top:
    default: op
  core.bottom:
    default: op
  core.whois:
    description: "Allows using the /whois command."
    default: true
  core.tpauto:
    default: true
  core.spawn:
    default: true
  core.setspawn:
    default: op
  core.help:
    default: true

  core.hide.group:
    default: false
  core.hide.bypass:
    default: op
  core.hide.default:
    default: true

  core.fly:
    default: op
  core.fly.others:
    default: op
  core.explode:
    default: op
  core.explode.others:
    default: op
  core.explode.exempt:
    default: op
  core.gc:
    default: true
  core.give:
    default: op
  core.itemdb:
    default: op
  core.msg:
    default: true
  core.heal:
    default: op
  core.heal.others:
    default: op
  core.heal.nocooldown:
    default: op
  core.feed:
    default: op
  core.feed.others:
    default: op
  core.feed.nocooldown:
    default: op
  core.rename:
    default: op
  core.lore:
    default: op
  core.god:
    default: op

  core.more:
    default: op

  chat.color:
    description: Allows using all colors in chat
    default: op
  chat.color.black:
    description: Allows using black color in chat
    default: op
  chat.color.dark_blue:
    description: Allows using dark blue color in chat
    default: op
  chat.color.dark_green:
    description: Allows using dark green color in chat
    default: op
  chat.color.dark_red:
    description: Allows using dark red color in chat
    default: op
  chat.color.dark_purple:
    description: Allows using dark purple color in chat
    default: op
  chat.color.gold:
    description: Allows using gold color in chat
    default: op
  chat.color.gray:
    description: Allows using gray color in chat
    default: op
  chat.color.dark_gray:
    description: Allows using dark gray color in chat
    default: op
  chat.color.blue:
    description: Allows using blue color in chat
    default: op
  chat.color.green:
    description: Allows using green color in chat
    default: op
  chat.color.aqua:
    description: Allows using aqua color in chat
    default: op
  chat.color.red:
    description: Allows using red color in chat
    default: op
  chat.color.light_purple:
    description: Allows using light purple color in chat
    default: op
  chat.color.yellow:
    description: Allows using yellow color in chat
    default: op
  chat.color.white:
    description: Allows using white color in chat
    default: op
  chat.unicode:
    description: Allows using unicode characters in chat
    default: op
  chat.color.hex:
    description: Allows using hex colors in chat
    default: op
  chat.format.bold:
    description: Allows using bold formatting in chat
    default: op
  chat.format.italic:
    description: Allows using italic formatting in chat
    default: op
  chat.format.reset:
    description: Allows using reset formatting in chat
    default: op
  chat.format.strikethrough:
    description: Allows using strikethrough formatting in chat
    default: op
  chat.format.underline:
    description: Allows using underline formatting in chat
    default: op
  chat.format.magic:
    description: Allows using magic formatting in chat
    default: op
