name: SFCore
version: 1.0
main: net.survivalfun.core.PluginStart
api-version: 1.21
author: towkio
description: "Survival Fun Core"

commands:
  explode:
    description: "Explodes target player"
    usage: "/explode <player> [modifier]"
    permission: core.explode
  gc:
    description: "Displays server details"
    usage: "/gc"
    permission: core.gc
  give:
    description: "Give items to players"
    usage: "/give <player> <item> <amount>"
    permission: core.give
    aliases: [i]
  itemdb:
    description: "Shows item/block info"
    usage: "/itemdb"
    permission: core.itemdb
  heal:
    description: "Heal players"
    usage: "/heal [player]"
    permission: core.heal

permissions:
  core.explode:
    default: op
  core.explode.self:
    default: op
  core.explode.exempt:
    default: op
  core.gc:
    default: true
