name: Allium
version: 0.1.3a
main: net.survivalfun.core.PluginStart
api-version: 1.21
author: towkio
description: "A secure, modern Essentials solution."
depend: [Vault]
soft-depend: [PlaceholderAPI]

commands:
  redeem:
    description: Allows eligible players to redeem a rank and rewards.
    usage: /redeem
    aliases: [claimrank] # Optional alias
  explode:
    description: "Explodes target player"
    usage: "/explode <player> [modifier]"
    permission: allium.explode
  gc:
    description: "Displays server details"
    usage: "/gc"
    permission: allium.gc
  give:
    description: "Give items to players"
    usage: "/give <player> <item> <amount>"
    permission: allium.give
    aliases: [i]
  itemdb:
    description: "Shows item/block info"
    usage: "/itemdb"
    permission: allium.itemdb
  heal:
    description: "Heal players"
    usage: "/heal [player]"
    permission: allium.heal
  feed:
    description: "Feed players"
    usage: "/feed [player]"
    permission: allium.feed
  core:
    description: "Core plugin command. Subcommands: reload, debug, voucher, etc."
    usage: "/core"
    permission: allium.admin
  rename:
    description: "Rename item in main hand"
    usage: "/rename <name>"
    permission: allium.rename
  lore:
    description: "Mange lore in main hand"
    usage: "/lore <add|remove|clear> <text>"
    permission: allium.lore
  god:
    description: "Toggle god mode"
    usage: "/god || /god <player>"
    permission: allium.god
  more:
    description: "Adds more items to your inventory"
    usage: "/more"
    permission: allium.more
  fly:
    description: "Toggle flight"
    usage: "/fly || /fly <player>"
    permission: allium.fly
  gamemode:
    description: "Change gamemode"
    usage: "/gamemode <gamemode> <player>"
    permission: allium.gamemode
    aliases: [gm, gmc, gms, gma, gmsp, survival, creative, adventure, spectator]
  nv:
    description: "Toggle night vision"
    usage: "/nv"
    permission: allium.nv
  msg:
    description: "Send a private message to player"
    usage: "/msg <player> <message>"
    aliases: [ tell, w, whisper, pm, message, m, t ]

  reply:
    description: "Reply to the last message received"
    usage: "/reply <message>"
    aliases: [ r ]

  mail:
    description: "Send or read offline messages"
    usage: "/mail <read|send|clear|gift|claim> [player] [message]"

  spy:
    description: "Spy on private messages"
    usage: "/spy [player]"
  help:
    description: "Displays help"
    usage: "/help [command]"
    aliases: [commands]
  spawn:
    description: "Teleports you to spawn"
    usage: "/spawn"
    aliases: [setspawn]
  
  skull:
    description: "Get a player's head"
    usage: "/skull <player>"
    permission: allium.skull
    aliases: [head, playerhead]
  
  home:
    description: "Teleports you to your home"
    usage: "/home [home]"
    permission: allium.home

  homes:
    description: "Lists your homes"
    usage: "/homes"
    permission: allium.homes
  
  sethome:
    description: "Sets a home"
    usage: "/sethome [home]"
    permission: allium.sethome
  
  delhome:
    description: "Deletes a home"
    usage: "/delhome [home]"
    permission: allium.delhome
    aliases: [removehome]
  
  # Economy commands
  balance:
    description: "Check your balance or another player's balance"
    usage: "/balance [player]"
    aliases: [bal]
    permission: allium.balance
  
  pay:
    description: "Pay another player"
    usage: "/pay <player> <amount>"
    permission: allium.pay
    
  baltop:
    description: "View the richest players"
    usage: "/baltop [page]"
    permission: allium.baltop
    
  money:
    description: "Admin command to manage player balances"
    usage: "/money <give|take|set|clear> <player> [amount]"
    permission: allium.money
  
  # Teleport Commands
  tp:
    description: "Teleport to a player or location"
    usage: "/tp [player] or /tp [x] [y] [z]"
    aliases: [tpo, teleport, back]
    permission: allium.tp
  
  tpa:
    description: "Request to teleport to a player"
    usage: "/tpa <player>"
    permission: allium.tpa
  
  tpcancel:
    description: "Cancel a teleport request"
    usage: "/tpcancel"
    aliases: [tpacancel]
    permission: allium.tpa
  
  tpaccept:
    description: "Accept a teleport request"
    usage: "/tpaccept [player]"
    aliases: [tpyes]
    permission: allium.tpa
  
  tpdeny:
    description: "Deny a teleport request"
    usage: "/tpdeny [player]"
    aliases: [tpno]
    permission: allium.tpa
  
  tppet:
    description: "Teleport your pets"
    usage: "/tppet"
    permission: allium.tppet
  
  tpmob:
    description: "Teleport your mobs"
    usage: "/tpmob"
    aliases: [tpentity, tpent, teleportmob, tpm, tpe]
    permission: allium.tpmob
  
  tppos:
    description: "Teleport to specific coordinates"
    usage: "/tppos <x> <y> <z> [yaw] [pitch]"
    permission: allium.tppos
  
  tphere:
    description: "Bring a player to your location"
    usage: "/tphere <player>"
    aliases: [s]
    permission: allium.tphere
  
  tpahere:
    description: "Request a player to teleport to you"
    usage: "/tpahere <player>"
    permission: allium.tpahere
  
  tptoggle:
    description: "Toggle teleport requests"
    usage: "/tptoggle [player]"
    permission: allium.tptoggle
  
  otp:
    description: "Teleport to a player's last known location"
    usage: "/otp <player>"
    aliases: [offlinetp, tpoffline]
    permission: allium.tp.offline
  
  top:
    description: "Teleport to the highest block"
    usage: "/top"
    permission: allium.top
  
  bottom:
    description: "Teleport to the lowest block"
    usage: "/bottom"
    permission: allium.bottom

  whois:
    description: "Displays detailed information about a player."
    usage: "/whois <player>"
    permission: allium.whois

  maintenance:
    description: "Toggle maintenance mode"
    usage: "/maintenance [on|off] [reason]"
    permission: allium.admin

  invsee:
    description: View and edit another player's inventory
    usage: /invsee <player>
    permission: allium.invsee

  enchant:
    description: Enchant an item in hand
    usage: /enchant <enchantment> [level]
    permission: allium.enchant

  note:
    description: Add a note about a player
    usage: /note <player> <note>
    permission: allium.staff
  notes:
    description: View player notes
    usage: /notes [player]
    permission: allium.staff
  unnote:
    description: Remove a player note
    usage: /unnote <player> <id>
    permission: allium.staff

  # Time commands
  time:
    description: "Manipulate or view the time"
    usage: "/time [set|add] [time] [world]"
    permission: allium.time
  day:
    description: "Set the time to day"
    usage: "/day [set|add] [time] [world]"
    permission: allium.time
  night:
    description: "Set the time to night"
    usage: "/night [set|add] [time] [world]"
    permission: allium.time

permissions:
  allium.staff:
    description: "Gives access to staff commands"
    default: op
    children:
      allium.escalate: true
      allium.spy: true
      allium.spy.others: true
      allium.gamemode: true
      allium.gamemode.spectator: true
      allium.note: true
      allium.notes: true
      allium.unnote: true
      allium.invsee: true
      allium.tp: true
      allium.tp.others: true
      allium.tp.offline: true
      allium.tp.override: true
      allium.tptoggle.others: true
      allium.tphere: true
      allium.tppos: true
      allium.tpa.nocooldown: true
      allium.feed.nocooldown: true
      allium.heal.nocooldown: true
      allium.tpa.nodelay: true
      allium.lockdown.bypass: true
  allium.admin:
    description: "Gives access to all core admin commands"
    default: op
    children:
      allium.debug: true
      allium.reload: true
      allium.hideupdate: true
      allium.hide: true
      allium.chatmod: true
      allium.enchant: true
      allium.staff: true

  allium.enchant:
    description: "Allows using the enchant command"
    default: op

  allium.spy:
    default: op
  
  allium.money:
    default: op
  allium.note:
    default: op
  allium.notes:
    default: op
  allium.unnote:
    default: op

  allium.gamemode.others:
    default: op
  allium.gamemode.survival:
    default: op
  allium.gamemode.survival.nv:
    default: op
  allium.gamemode.creative:
    default: op
  allium.gamemode.creative.inventory:
    default: op
  allium.gamemode.creative.container:
    default: op
  allium.gamemode.creative.pickup:
    default: op
  allium.gamemode.creative.drop:
    default: op
  allium.gamemode.creative.break:
    default: op
  allium.gamemode.creative.place:
    default: op
  allium.gamemode.creative.interact:
    default: op
  allium.gamemode.creative.use:
    default: op
  allium.gamemode.creative.spawn:
    default: op
  allium.gamemode.creative.blacklist:
    default: op
  allium.gamemode.creative.nv:
    default: op
  allium.gamemode.adventure:
    default: op
  allium.gamemode.adventure.nv:
    default: op
  allium.gamemode.spectator:
    default: op
  allium.gamemode:
    default: op
  allium.nv:
    default: op
  allium.nv.others:
    default: op
  allium.nv.adventure:
    default: op
  allium.nv.creative:
    default: op
  allium.nv.spectator:
    default: op
  allium.nv.survival:
    default: op

  allium.tp:
    default: op
  allium.tp.others:
    default: op
  allium.tp.override:
    default: op
  allium.tp.offline:
    default: op
  allium.tpa:
    default: true
  allium.tpa.nodelay:
    default: op
  allium.tpa.nocooldown:
    default: op
  allium.voucher.give:
    description: "Allows giving rank vouchers via /core voucher give"
    default: op
  allium.tppos:
    default: op
  allium.lockdown.bypass:
    default: op
  allium.tphere:
    default: op
  allium.tpahere:
    default: true
  allium.tpall:
    default: op
  allium.tptoggle:
    default: true
  allium.tptoggle.others:
    default: op
  allium.top:
    default: op
  allium.bottom:
    default: op
  allium.whois:
    description: "Allows using the /whois command."
    default: true
  allium.tpauto:
    default: true
  allium.spawn:
    default: true
  allium.setspawn:
    default: op
  allium.help:
    default: true

  allium.home:
    default: true
  allium.sethome:
    default: true
  allium.homes:
    default: true
  allium.delhome:
    default: true
  allium.sethome.unlimited:
    default: op
  allium.home.others:
    default: op
  allium.home.nocooldown:
    default: op

  allium.hide.group:
    default: false
  allium.hide.bypass:
    default: op
  allium.hide.default:
    default: true

  allium.fly:
    default: op
  allium.fly.others:
    default: op
  allium.explode:
    default: op
  allium.explode.others:
    default: op
  allium.explode.exempt:
    default: op
  allium.gc:
    default: true
  allium.give:
    default: op
  allium.itemdb:
    default: op
  allium.msg:
    default: true
  allium.heal:
    default: op
  allium.heal.others:
    default: op
  allium.heal.nocooldown:
    default: op
  allium.feed:
    default: op
  allium.feed.others:
    default: op
  allium.feed.nocooldown:
    default: op
  allium.rename:
    default: op
  allium.lore:
    default: op
  allium.god:
    default: op
  allium.pay:
    default: true
  allium.balance:
    default: true
  allium.baltop:
    default: true

  allium.more:
    default: op

  chat.color:
    description: Allows using all colors in chat
    default: op
  chat.color.black:
    description: Allows using black color in chat
    default: op
  chat.color.dark_blue:
    description: Allows using dark blue color in chat
    default: op
  chat.color.dark_green:
    description: Allows using dark green color in chat
    default: op
  chat.color.dark_red:
    description: Allows using dark red color in chat
    default: op
  chat.color.dark_purple:
    description: Allows using dark purple color in chat
    default: op
  chat.color.gold:
    description: Allows using gold color in chat
    default: op
  chat.color.gray:
    description: Allows using gray color in chat
    default: op
  chat.color.dark_gray:
    description: Allows using dark gray color in chat
    default: op
  chat.color.blue:
    description: Allows using blue color in chat
    default: op
  chat.color.green:
    description: Allows using green color in chat
    default: op
  chat.color.aqua:
    description: Allows using aqua color in chat
    default: op
  chat.color.red:
    description: Allows using red color in chat
    default: op
  chat.color.light_purple:
    description: Allows using light purple color in chat
    default: op
  chat.color.yellow:
    description: Allows using yellow color in chat
    default: op
  chat.color.white:
    description: Allows using white color in chat
    default: op
  chat.unicode:
    description: Allows using unicode characters in chat
    default: op
  chat.color.hex:
    description: Allows using hex colors in chat
    default: op
  chat.format.bold:
    description: Allows using bold formatting in chat
    default: op
  chat.format.italic:
    description: Allows using italic formatting in chat
    default: op
  chat.format.reset:
    description: Allows using reset formatting in chat
    default: op
  chat.placeholderapi:
    description: Allows using PlaceholderAPI placeholders in chat
    default: op
  chat.format.strikethrough:
    description: Allows using strikethrough formatting in chat
    default: op
  chat.format.underline:
    description: Allows using underline formatting in chat
    default: op
  chat.format.magic:
    description: Allows using magic formatting in chat
    default: op

  allium.time:
    description: "Allows the player to view the time"
    default: true
  allium.time.set:
    description: "Allows the player to set the time"
    default: op
  allium.time.add:
    description: "Allows the player to add to the time"
    default: op
